### ISSUE TITLE
change folder name from torchaudio-contrib to torchaudio_contrib

### ISSUE THREAD

**Issue by tsauri** [keunwoochoi/torchaudio-contrib#26]
Because you cannot import with a - ( subtract operator)

**Comment by keunwoochoi** [comment]
Thanks. If other maintainers have no specific veto, I'll do it later. Or you can PR too.

**Comment by f0k** [comment]
No veto. But is it meant to be imported? :)

**Comment by drscotthawley** [comment]
Was just opening a new issue about exactly this, when I saw this open Issue.  Pasting in what I said...  


Hey guys, great that you're doing this.  I wanted to make this easy to try out and include in other code via `import torchaudio-contrib`, but the hyphen in the name "torchaudio-contrib" is a problem: Python doesn't allow hyphens, only underscores. 

Would you consider changing the main sub-directory name to "torchaudio_contrib"?  If you do, then I've got a setup.py file for you:

```
$ cat setup.py

from setuptools import setup

setup(name='torchaudio_contrib',
      version='0.1',
      description='To propose audio processing Pytorch codes with nice and easy-to-use APIs and functionality',
      url='https://github.com/keunwoochoi/torchaudio-contrib',
      author='Keunwoo Choi, Faro Stöter, Kiran Sanjeevan',
      author_email='',
      license='MIT',
      packages=['torchaudio_contrib'],
      zip_safe=False)
```

So that one can install via `pip install .` And it can be imported via `import torchaudio_contrib`.

**Comment by drscotthawley** [comment]
Add pull request https://github.com/keunwoochoi/torchaudio-contrib/pull/30
